### ISSUE TITLE
Fixity of `(<$>)`

### ISSUE THREAD

**Issue by endgame** [blamario/grampa#21]
`(<$>)` does not have a fixity annotation. Should it?

**Comment by blamario** [comment]
But it does:

https://github.com/blamario/grampa/commit/5f858d6dbadbe7d9a280e61b0a920be40f50bca3

**Comment by endgame** [comment]
Oh cool, thanks. That version must not have hit nixpkgs or hackage yet.

**Comment by blamario** [comment]
Version 1.4 has the fix released.
