### ISSUE TITLE
Build failure with GHC-8.0

### ISSUE THREAD

**Issue by phadej** [blamario/grampa#26]
rank2classes-1.4.3 fails with

```
src/Rank2.hs:242:18: error:
    • Expected kind ‘(k0 -> *) -> *’,
        but ‘Generics.V1’ has kind ‘* -> *’
    • In the first argument of ‘Functor’, namely ‘Generics.V1’
      In the instance declaration for ‘Functor Generics.V1’
```

I made a revision https://hackage.haskell.org/package/rank2classes-1.4.3/revisions/

**Comment by blamario** [comment]
Thanks, fixed by https://github.com/blamario/grampa/commit/d2c655365e8efcb00404040f9a48582f399d9d4c
