### ISSUE TITLE
Consider dropping Product

### ISSUE THREAD

**Issue by treeowl** [blamario/grampa#6]
Now that `Data.Functor.Product.Product` is polykinded, I'm not sure `rank2classes` really needs its own. The main difference is that your version has `fst` and `snd` fields while the one in `base` doesn't.

**Comment by blamario** [comment]
Yes, you have a point there. I *think* the only reason for the duplication is that I wrote the library before `base-4.9` was out, but now that I depend on it anyway for the `Semigroup` I might as well use the `base` definition of `Product`.

**Comment by blamario** [comment]
Fixed by c02d669ffea198c03f3b694b79bb26ef2842a6bc

I kept the fst/snd field accessors, but I decided against the full pattern synonyms. This necessitates version 1.1 release.
