### ISSUE TITLE
Add instances for Data.Functor.Sum

### ISSUE THREAD

**Issue by treeowl** [blamario/grampa#8]
It seems to have been left out for some reason.

**Comment by blamario** [comment]
The reason is,  it was still fresh when I first released the library, and I didn't want to depend on `base >= 4.9`. I can certainly add it now.

**Comment by blamario** [comment]
Fixed by 336f9d8b45af5aedc0a54be9e9647efa2e6b80db

There are no instances for `Apply` and `Distributive` classes, because their methoids would be partial. This made me realize that `Rank2.TH` was generating partial instances of these classes for multi-constructor data types. I've removed those.
