### ISSUE TITLE
Why are product instances so lazy?

### ISSUE THREAD

**Issue by treeowl** [blamario/grampa#9]
Lazy instances don't tend to follow laws terribly nicely, and can easily lead to performance problems. Why is it done this way?

**Comment by blamario** [comment]
I can dig in if you want lower-level details, but the short answer is that `fixGrammar` from `grammatical-parsers` didn't work with anything stricter.

**Comment by treeowl** [comment]
Hrmmmm. Maybe keep your Product as a lazy one and add the other with the
strict instances?

**Comment by blamario** [comment]
> Maybe keep your Product as a lazy one and add the other with the strict instances?

It's not just Product. If you look around, you'll find that instances of *all* single-constructor data types are as lazy, including those generated by `Rank2.TH`.

The laziness is most important for the `Rank2.Applicative` methods, but it spilled over to the other classes for consistency. The function [http://hackage.haskell.org/package/grammatical-parsers-0.2.2/docs/Text-Grampa-ContextFree-LeftRecursive.html#v:parseSeparated](parseSeparated) strongly depends on the laziness of `liftA3`, but there may be other cases.

**Comment by blamario** [comment]
As of 7de215f1c9dcda4cdb4fd85a7e3f6d4583a8e89c the only non-strict arguments are the RHS of `Rank2.<*>`  and the third and following arguments of `Rank.liftAn`. That's as strict as they can get to keep the higher-level algorithms working.

I hope that settles the issue.
